version: '3'

volumes:
  database:

services:

  #Nginx reverse proxy
  nginx:
    build: Frontend/
    container_name: vir2em-ui
    ports:
      - '8000:80'
      - '8001:81'
      - '8002:82'
    volumes:
      - ./Frontend/dist/my-app/:/usr/share/nginx/html:rw
      - ./Frontend/src/nginx/:/etc/nginx/:rw
    depends_on:
      - flask
    restart: always

  #API Flask
  flask:
    container_name: backend
    build: Backend/
    restart: always
    depends_on:
      - database

  #Postgres database
  database:
    build: Backend/database
    container_name: database
    restart: always
    volumes:
      - database:/var/lib/postgresql/data:rw
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres