version: '3'

volumes:
  database:

services:
  frontend:
    build: Frontend/
    container_name: vir2em-ui
    ports:
      - '8000:80'
    volumes:
      - ./Frontend/dist/my-app/:/usr/share/nginx/html:rw
      - ./Frontend/src/nginx/:/etc/nginx/:rw
    depends_on:
      - backend
    restart: always

  backend:
    container_name: backend
    build: Backend/
    ports:
      - '9000:5000'
    restart: always
    depends_on:
      - database

  database:
    build: Backend/database
    container_name: database
    ports:
      - '10000:5432' #Default di postgres.
    restart: always
    volumes:
      - database:/var/lib/postgresql/data:rw
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres