version: '3'

volumes:
  database_data:

services:

  #Nginx reverse proxy
  nginx:
    build: Frontend/
    container_name: vir2em-ui
    ports:
      - '157.138.24.164:8000:80'
    volumes:
      - ./Frontend/dist/my-app/:/usr/share/nginx/html:rw
      - ./Frontend/src/nginx/:/etc/nginx/:rw
    depends_on:
      - flask
    restart: always

  #API Flask
  flask:
    container_name: backend
    build: Backend/
    restart: always
    depends_on:
      - database
    ports:
      - '157.138.24.164:9000:6000'

  #Postgres database
  database:
    build: Backend/database
    container_name: database
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      - ./Backend/database/:/docker-entrypoint-initdb.d/:ro
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6543:5432'
