controllername = "NAME"
ip = "IP"
port = "PORT"
db_type = "DATABASETYPE"
db_name = "DATABASENAME"
db_pw = "DATABSEPASSWORD"
db_ip = "DATABASEIP"
db_port = "DATABASEPORT"
db_admin_name = "DATABASEADMINNAME"
db_admin_password = "DATABASEADMINPASSWORD"
logs = "LOGSPATH"
# L'unico scopo del file è contenere tutte le keyword usate nel programma per le variabili ottenute dal parser
