version: '3'
services:
  frontend:
    build: . #Buildo con dockerfile
    container_name: Vir2em
    expose:
      - 8080:80
    volumes:
      - ./dist/my-app/:/usr/share/nginx/html:ro
      - ./src/nginx/:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: always
  
  backend:
    build: .

    restart: always
    
  db:
    build: ./database
    container_name: database
    expose:
      - 9000:5432 #Default di postgres.
    restart: always
    
